export const enablePayment = true
// export const maxFileSize =  5

export const enableDonation = false

export const FILE_UPLOAD_SIZE = 5

export const POST_TITLE_CHARACTER_LIMIT = 100
export const POST_DESC_CHARACTER_LIMIT = 10000
export const POST_TITLE_MIN_CHARACTER_LIMIT = 50
export const POST_DESC_MIN_CHARACTER_LIMIT = 100
export const PRICING_DESC_CHARACTER_LIMIT = 300

// // export const tags_to_filter_out='["Education", ".", "Service", "Types", "Level", "More", "Information", "Other", "more", "other"]'

export const DEFAULT_PRICE_RANGE = '20,37'
export const CONTACT_EMAIL_TO = 'contact@1stkare.com'
export const EMAIL_FROM = '1stKare <noreply@1stkare.com>'

// export const NEXT_PUBLIC_BLOG_URL = 'https://1stkare-blog-web-psi.vercel.app'
export const NEXT_PUBLIC_BLOG_URL = 'https://blog.1stkare.com'
export let STRIPE_PRODUCT_DONATION = ''
export let STRIPE_PRODUCT_POST_SUBSCRIPTION_NATIONAL_BUSINESS = ''
export let STRIPE_PRODUCT_POST_SPONSORSHIP_INDIVIDUAL = ''
export let STRIPE_PRODUCT_POST_SPONSORSHIP_BUSINESS = ''
export let STRIPE_PRODUCT_POST_SUBSCRIPTION_INDIVIDUAL = ''
export let STRIPE_PRODUCT_POST_SUBSCRIPTION_BUSINESS = ''

export const STRIPE_PRODUCT_USER_SUBSCRIPTION = ''

export let NEXT_PUBLIC_PAYPAL_SPONSORSHIP_INDIVIDUAL = ''
export let NEXT_PUBLIC_PAYPAL_SPONSORSHIP_BUSINESS = ''
export let NEXT_PUBLIC_PAYPAL_SUBSCRIPTION_INDIVIDUAL = ''
export let NEXT_PUBLIC_PAYPAL_SUBSCRIPTION_BUSINESS = ''

export let NEXT_PUBLIC_PAYPAL_SUBSCRIPTION_NATIONAL_BUSINESS = ''

export let NEXT_PUBLIC_PAYPAL_API_URL = ''

if (process.env.NODE_ENV == 'development') {
  // sandbox
  NEXT_PUBLIC_PAYPAL_SPONSORSHIP_INDIVIDUAL = 'P-23T91467205141038MJR6WLA'
  NEXT_PUBLIC_PAYPAL_SPONSORSHIP_BUSINESS = 'P-5JJ7959919219682GMJR6V6Y'
  NEXT_PUBLIC_PAYPAL_SUBSCRIPTION_INDIVIDUAL = 'P-0G107863L07705802MJR6XLY'
  NEXT_PUBLIC_PAYPAL_SUBSCRIPTION_BUSINESS = 'P-8M126598CP7619104MJR6VLI'

  NEXT_PUBLIC_PAYPAL_SUBSCRIPTION_NATIONAL_BUSINESS =
    'P-9U0127922N042533GMJ6VB3Y'

  NEXT_PUBLIC_PAYPAL_API_URL = 'https://api-m.sandbox.paypal.com'

  STRIPE_PRODUCT_DONATION = 'prod_KuBFF0ZQ94REIh'
  STRIPE_PRODUCT_POST_SUBSCRIPTION_NATIONAL_BUSINESS = 'prod_KuBDcr0MiV2Lcb'
  STRIPE_PRODUCT_POST_SPONSORSHIP_INDIVIDUAL = 'prod_KuBBH6xKF72Alh'
  STRIPE_PRODUCT_POST_SPONSORSHIP_BUSINESS = 'prod_KuBAH0wV87lrGW'
  STRIPE_PRODUCT_POST_SUBSCRIPTION_INDIVIDUAL = 'prod_KuB9TL0lnwvWjb'
  STRIPE_PRODUCT_POST_SUBSCRIPTION_BUSINESS = 'prod_KuB6H9IUAyojSb'
} else {
  // production
  NEXT_PUBLIC_PAYPAL_SPONSORSHIP_INDIVIDUAL = 'P-8HN68341SS4179328MJRTAXQ'
  NEXT_PUBLIC_PAYPAL_SPONSORSHIP_BUSINESS = 'P-8876834678640544AMJRTC5Y'
  NEXT_PUBLIC_PAYPAL_SUBSCRIPTION_INDIVIDUAL = 'P-1PV37349FN188541GMJRORFI'
  NEXT_PUBLIC_PAYPAL_SUBSCRIPTION_BUSINESS = 'P-07R73245SY094602YMJRTCGY'

  NEXT_PUBLIC_PAYPAL_SUBSCRIPTION_NATIONAL_BUSINESS =
    'P-26Y0299318389180TMJRTD5Q'

  NEXT_PUBLIC_PAYPAL_API_URL = 'https://api-m.paypal.com'

  // STRIPE_PRODUCT_DONATION = 'prod_KuBFF0ZQ94REIh'
  STRIPE_PRODUCT_POST_SUBSCRIPTION_NATIONAL_BUSINESS = 'prod_Jzvk6Ouqgn5Lj9'
  STRIPE_PRODUCT_POST_SPONSORSHIP_INDIVIDUAL = 'prod_KuBOEFhX26nL8q'
  STRIPE_PRODUCT_POST_SPONSORSHIP_BUSINESS = 'prod_JzvaqteGE5eEKE'
  STRIPE_PRODUCT_POST_SUBSCRIPTION_INDIVIDUAL = 'prod_JzvdOobiyBaZZU'
  STRIPE_PRODUCT_POST_SUBSCRIPTION_BUSINESS = 'prod_JzvhXB54E7IF97'
}
